import fs from 'node:fs/promises';
import path from 'node:path';
import { PublicKey } from '@solana/web3.js';

const ROOT = process.cwd();
const REGISTRY_PATH = path.join(ROOT, 'public', 'idl', 'registry.json');
const PUBLIC_IDL_DIR = path.join(ROOT, 'public', 'idl');

function fail(message) {
  throw new Error(message);
}

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) {
      continue;
    }
    const key = token.slice(2);
    const next = argv[i + 1];
    if (!next || next.startsWith('--')) {
      out[key] = true;
      continue;
    }
    out[key] = next;
    i += 1;
  }
  return out;
}

function asNonEmptyString(value, label) {
  if (typeof value !== 'string' || value.trim().length === 0) {
    fail(`${label} is required.`);
  }
  return value.trim();
}

function toSlug(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '') || 'protocol_pack';
}

function assertPubkey(value, label) {
  try {
    return new PublicKey(value).toBase58();
  } catch {
    fail(`${label} must be a valid Solana public key.`);
  }
}

async function pathExists(filepath) {
  try {
    await fs.access(filepath);
    return true;
  } catch {
    return false;
  }
}

async function readJson(filepath, label) {
  const raw = await fs.readFile(filepath, 'utf8').catch(() => null);
  if (raw === null) {
    fail(`${label} not found: ${path.relative(ROOT, filepath)}`);
  }
  try {
    return JSON.parse(raw);
  } catch {
    fail(`${label} is not valid JSON: ${path.relative(ROOT, filepath)}`);
  }
}

function createCodamaSkeleton(programId, name) {
  return {
    kind: 'rootNode',
    standard: 'codama',
    version: '1.0.0',
    program: {
      kind: 'programNode',
      name,
      publicKey: programId,
      version: '0.1.0',
      origin: 'manual',
      docs: ['Starter Codama scaffold generated by pack-init.'],
      accounts: [],
      instructions: [],
      definedTypes: [],
      pdas: [],
      errors: [],
    },
  };
}

function createIndexingSkeleton({ protocolId, programId, codamaAssetPath }) {
  return {
    schema: 'declarative-decoder-runtime.v1',
    protocolId,
    version: '0.1.0',
    label: `${protocolId} Indexing Spec`,
    programId,
    decoderArtifacts: {
      default: {
        kind: 'generated_idl_decoder',
        family: 'codama',
        artifact: toSlug(protocolId),
        codamaPath: codamaAssetPath,
      },
    },
    sources: {},
    matchRules: [],
    pipelines: {},
    projectionSpecs: {},
    operations: {},
    notes: [
      `Starter indexing spec for ${protocolId}.`,
      `Add sources/matchRules/pipelines/projections for program ${programId}.`,
    ],
  };
}

function createAgentRuntimeSkeleton({ protocolId, programId, codamaAssetPath }) {
  void protocolId;
  void programId;
  void codamaAssetPath;
  return {
    $schema: '/idl/solana_agent_runtime.schema.v1.json',
    schema: 'solana-agent-runtime.v1',
    computes: {},
    contract_writes: {},
  };
}

function normalizeCommands(raw) {
  if (!raw || raw === true) {
    return [];
  }
  return String(raw)
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean)
    .map((item) => {
      if (!item.startsWith('/')) {
        fail(`command must start with '/': ${item}`);
      }
      return item;
    });
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    console.log('Usage: npm run pack:init -- --id <protocol-id> --name <display-name> --program-id <pubkey> [--network mainnet-beta] [--slug protocol_slug] [--transport local-transport] [--status inactive|active] [--commands /cmd1,/cmd2] [--overwrite]');
    return;
  }

  const protocolId = asNonEmptyString(args.id, '--id');
  const name = asNonEmptyString(args.name, '--name');
  const programId = assertPubkey(asNonEmptyString(args['program-id'], '--program-id'), '--program-id');
  const network = typeof args.network === 'string' ? args.network : 'mainnet-beta';
  const slug = typeof args.slug === 'string' ? toSlug(args.slug) : toSlug(protocolId);
  const transport = typeof args.transport === 'string' ? args.transport : `local-${protocolId}`;
  const status = typeof args.status === 'string' ? args.status : 'inactive';
  const commands = normalizeCommands(args.commands ?? args.command);
  const overwrite = Boolean(args.overwrite);

  const codamaPath = path.join(PUBLIC_IDL_DIR, `${slug}.codama.json`);
  const agentRuntimePath = path.join(PUBLIC_IDL_DIR, `${slug}.runtime.json`);
  const indexingSpecPath = path.join(PUBLIC_IDL_DIR, `${slug}.indexing.json`);

  if (!overwrite) {
    if (await pathExists(codamaPath)) {
      fail(`Codama file already exists: ${path.relative(ROOT, codamaPath)} (use --overwrite to replace)`);
    }
    if (await pathExists(agentRuntimePath)) {
      fail(`Agent runtime already exists: ${path.relative(ROOT, agentRuntimePath)} (use --overwrite to replace)`);
    }
    if (await pathExists(indexingSpecPath)) {
      fail(`Indexing spec already exists: ${path.relative(ROOT, indexingSpecPath)} (use --overwrite to replace)`);
    }
  }

  await fs.mkdir(PUBLIC_IDL_DIR, { recursive: true });

  const codamaJson = createCodamaSkeleton(programId, slug);
  const codamaAssetPath = `/idl/${slug}.codama.json`;
  const runtimeJson = createAgentRuntimeSkeleton({ protocolId, programId, codamaAssetPath });
  const indexingJson = createIndexingSkeleton({ protocolId, programId, codamaAssetPath });

  await fs.writeFile(codamaPath, `${JSON.stringify(codamaJson, null, 2)}\n`, 'utf8');
  await fs.writeFile(agentRuntimePath, `${JSON.stringify(runtimeJson, null, 2)}\n`, 'utf8');
  await fs.writeFile(indexingSpecPath, `${JSON.stringify(indexingJson, null, 2)}\n`, 'utf8');

  const registry = await readJson(REGISTRY_PATH, 'Registry');
  if (!registry || typeof registry !== 'object' || !Array.isArray(registry.protocols)) {
    fail('public/idl/registry.json has invalid shape.');
  }

  const nextEntry = {
    id: protocolId,
    name,
    network,
    programId,
    codamaIdlPath: `/idl/${slug}.codama.json`,
    agentRuntimePath: `/idl/${slug}.runtime.json`,
    indexingSpecPath: `/idl/${slug}.indexing.json`,
    transport,
    supportedCommands: commands,
    status,
  };

  const existingIndex = registry.protocols.findIndex((item) => item && typeof item === 'object' && item.id === protocolId);
  if (existingIndex >= 0) {
    if (!overwrite) {
      fail(`Protocol id already exists in registry: ${protocolId} (use --overwrite to update)`);
    }
    registry.protocols[existingIndex] = nextEntry;
  } else {
    registry.protocols.push(nextEntry);
  }

  registry.protocols.sort((a, b) => String(a.id).localeCompare(String(b.id)));
  await fs.writeFile(REGISTRY_PATH, `${JSON.stringify(registry, null, 2)}\n`, 'utf8');

  console.log('Protocol pack scaffold created:');
  console.log(`- ${path.relative(ROOT, codamaPath)}`);
  console.log(`- ${path.relative(ROOT, agentRuntimePath)}`);
  console.log(`- ${path.relative(ROOT, indexingSpecPath)}`);
  console.log(`- ${path.relative(ROOT, REGISTRY_PATH)} updated`);
  console.log('');
  console.log('Next steps:');
  console.log('1. Make public/idl/<slug>.codama.json the protocol source of truth.');
  console.log('2. Fill public/idl/<slug>.indexing.json with sources, matchRules, pipelines, and projections.');
  console.log('3. Fill public/idl/<slug>.runtime.json with agent index views, computes, contract writes, and templates if needed.');
  console.log('4. Run: npm run codama:check');
  console.log('5. Run: npm run pack:doctor -- --protocol <protocol-id>');
  console.log('6. Run: npm run pack:check');
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
