import fs from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { PublicKey } from '@solana/web3.js';

const ROOT = process.cwd();
const REGISTRY_PATH = path.join(ROOT, 'public', 'idl', 'registry.json');
const AIDL_DIR = path.join(ROOT, 'aidl');
const PUBLIC_IDL_DIR = path.join(ROOT, 'public', 'idl');

function fail(message) {
  throw new Error(message);
}

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) {
      continue;
    }
    const key = token.slice(2);
    const next = argv[i + 1];
    if (!next || next.startsWith('--')) {
      out[key] = true;
      continue;
    }
    out[key] = next;
    i += 1;
  }
  return out;
}

function asNonEmptyString(value, label) {
  if (typeof value !== 'string' || value.trim().length === 0) {
    fail(`${label} is required.`);
  }
  return value.trim();
}

function toSlug(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '') || 'protocol_pack';
}

function assertPubkey(value, label) {
  try {
    return new PublicKey(value).toBase58();
  } catch {
    fail(`${label} must be a valid Solana public key.`);
  }
}

async function pathExists(filepath) {
  try {
    await fs.access(filepath);
    return true;
  } catch {
    return false;
  }
}

async function readJson(filepath, label) {
  const raw = await fs.readFile(filepath, 'utf8').catch(() => null);
  if (raw === null) {
    fail(`${label} not found: ${path.relative(ROOT, filepath)}`);
  }
  try {
    return JSON.parse(raw);
  } catch {
    fail(`${label} is not valid JSON: ${path.relative(ROOT, filepath)}`);
  }
}

function createIdlSkeleton(programId, name) {
  return {
    address: programId,
    metadata: {
      name,
      version: '0.1.0',
      spec: '0.1.0',
      description: 'Starter IDL scaffold generated by pack-init.',
    },
    instructions: [],
    accounts: [],
    types: [],
    events: [],
    errors: [],
  };
}

function createAidlSkeleton({ protocolId, slug }) {
  const templateName = `${protocolId}.read.health.v1`;
  return {
    kind: 'aidl.v0.1',
    target: {
      output: `public/idl/${slug}.meta.json`,
      schema: 'meta-idl.v0.6',
      schemaPath: '/idl/meta_idl.schema.v0.6.json',
      version: '0.1.0',
      protocolId,
    },
    templates: {
      [templateName]: {
        expand: {
          inputs: {
            note: { type: 'string', required: false, default: 'ready' },
          },
          discover: [],
          derive: [],
          compute: [],
          args: {},
          accounts: {},
        },
      },
    },
    operations: {
      health_read: {
        label: 'Health Read',
        use: [
          {
            template: templateName,
            with: {},
          },
        ],
      },
    },
    apps: {
      health_app: {
        title: 'Health Check',
        description: 'Starter read-only app. Replace with real protocol workflows.',
        entry_step: 'health',
        steps: [
          {
            id: 'health',
            label: 'Health',
            operation: 'health_read',
            title: 'Health Read',
            requires_paths: [],
            status_text: {
              running: 'Loading health check...',
              success: 'Health check completed.',
              error: 'Health check failed: {error}'
            },
            actions: [
              {
                label: 'Run Health Check',
                do: {
                  fn: 'run',
                  mode: 'view'
                }
              }
            ]
          },
        ],
        label: 'Health Check'
      },
    },
  };
}

function createRuntimeSkeleton({ protocolId, programId }) {
  return {
    schema: 'declarative-decoder-runtime.v1',
    protocolId,
    version: '0.1.0',
    decoderArtifacts: [],
    sources: [],
    projectionSpecs: {},
    notes: [
      `Starter runtime spec for ${protocolId}.`,
      `Add sources/matchRules/pipelines/compute/emit for program ${programId}.`,
    ],
  };
}

function normalizeCommands(raw) {
  if (!raw || raw === true) {
    return [];
  }
  return String(raw)
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean)
    .map((item) => {
      if (!item.startsWith('/')) {
        fail(`command must start with '/': ${item}`);
      }
      return item;
    });
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    console.log('Usage: npm run pack:init -- --id <protocol-id> --name <display-name> --program-id <pubkey> [--network mainnet-beta] [--slug protocol_slug] [--transport local-transport] [--status inactive|active] [--commands /cmd1,/cmd2] [--overwrite]');
    return;
  }

  const protocolId = asNonEmptyString(args.id, '--id');
  const name = asNonEmptyString(args.name, '--name');
  const programId = assertPubkey(asNonEmptyString(args['program-id'], '--program-id'), '--program-id');
  const network = typeof args.network === 'string' ? args.network : 'mainnet-beta';
  const slug = typeof args.slug === 'string' ? toSlug(args.slug) : toSlug(protocolId);
  const transport = typeof args.transport === 'string' ? args.transport : `local-${protocolId}`;
  const status = typeof args.status === 'string' ? args.status : 'inactive';
  const commands = normalizeCommands(args.commands ?? args.command);
  const overwrite = Boolean(args.overwrite);

  const aidlPath = path.join(AIDL_DIR, `${slug}.aidl.json`);
  const idlPath = path.join(PUBLIC_IDL_DIR, `${slug}.json`);
  const codamaPath = path.join(PUBLIC_IDL_DIR, `${slug}.codama.json`);
  const runtimePath = path.join(PUBLIC_IDL_DIR, `${slug}.runtime.json`);

  if (!overwrite) {
    if (await pathExists(aidlPath)) {
      fail(`AIDL file already exists: ${path.relative(ROOT, aidlPath)} (use --overwrite to replace)`);
    }
    if (await pathExists(idlPath)) {
      fail(`IDL file already exists: ${path.relative(ROOT, idlPath)} (use --overwrite to replace)`);
    }
    if (await pathExists(codamaPath)) {
      fail(`Codama file already exists: ${path.relative(ROOT, codamaPath)} (use --overwrite to replace)`);
    }
    if (await pathExists(runtimePath)) {
      fail(`Runtime spec already exists: ${path.relative(ROOT, runtimePath)} (use --overwrite to replace)`);
    }
  }

  await fs.mkdir(AIDL_DIR, { recursive: true });
  await fs.mkdir(PUBLIC_IDL_DIR, { recursive: true });

  const idlJson = createIdlSkeleton(programId, slug);
  const aidlJson = createAidlSkeleton({ protocolId, slug });
  const runtimeJson = createRuntimeSkeleton({ protocolId, programId });

  await fs.writeFile(idlPath, `${JSON.stringify(idlJson, null, 2)}\n`, 'utf8');
  await fs.writeFile(aidlPath, `${JSON.stringify(aidlJson, null, 2)}\n`, 'utf8');
  await fs.writeFile(runtimePath, `${JSON.stringify(runtimeJson, null, 2)}\n`, 'utf8');

  const registry = await readJson(REGISTRY_PATH, 'Registry');
  if (!registry || typeof registry !== 'object' || !Array.isArray(registry.protocols)) {
    fail('public/idl/registry.json has invalid shape.');
  }

  const nextEntry = {
    id: protocolId,
    name,
    network,
    programId,
    idlPath: `/idl/${slug}.json`,
    codamaIdlPath: `/idl/${slug}.codama.json`,
    runtimeSpecPath: `/idl/${slug}.runtime.json`,
    appPath: `/idl/${slug}.app.json`,
    transport,
    supportedCommands: commands,
    status,
  };

  const existingIndex = registry.protocols.findIndex((item) => item && typeof item === 'object' && item.id === protocolId);
  if (existingIndex >= 0) {
    if (!overwrite) {
      fail(`Protocol id already exists in registry: ${protocolId} (use --overwrite to update)`);
    }
    registry.protocols[existingIndex] = nextEntry;
  } else {
    registry.protocols.push(nextEntry);
  }

  registry.protocols.sort((a, b) => String(a.id).localeCompare(String(b.id)));
  await fs.writeFile(REGISTRY_PATH, `${JSON.stringify(registry, null, 2)}\n`, 'utf8');

  const compile = spawnSync('node', ['scripts/compile-aidl.mjs'], {
    cwd: ROOT,
    encoding: 'utf8',
  });

  if (compile.status !== 0) {
    const stderr = compile.stderr?.trim();
    const stdout = compile.stdout?.trim();
    fail([
      'pack-init created files but AIDL compile failed.',
      stderr || stdout || 'No compiler output.',
    ].join('\n'));
  }

  const codamaBootstrap = spawnSync('node', ['scripts/compile-codama.mjs'], {
    cwd: ROOT,
    encoding: 'utf8',
  });

  if (codamaBootstrap.status !== 0) {
    const stderr = codamaBootstrap.stderr?.trim();
    const stdout = codamaBootstrap.stdout?.trim();
    fail([
      'pack-init created files but Codama bootstrap failed.',
      stderr || stdout || 'No codama bootstrap output.',
    ].join('\n'));
  }

  console.log('Protocol pack scaffold created:');
  console.log(`- ${path.relative(ROOT, aidlPath)}`);
  console.log(`- ${path.relative(ROOT, idlPath)}`);
  console.log(`- ${path.relative(ROOT, codamaPath)}`);
  console.log(`- ${path.relative(ROOT, runtimePath)}`);
  console.log(`- ${path.relative(ROOT, REGISTRY_PATH)} updated`);
  console.log('');
  console.log('Next steps:');
  console.log('1. Make public/idl/<slug>.codama.json the protocol source of truth.');
  console.log('2. Keep public/idl/<slug>.json only as codec/compatibility IDL while needed.');
  console.log('3. Replace health_read in aidl/<slug>.aidl.json with real operations/templates/apps.');
  console.log('4. Fill public/idl/<slug>.runtime.json with sources/matchRules/pipelines/projections.');
  console.log('5. Run: npm run aidl:compile');
  console.log('6. Run: npm run codama:check');
  console.log('7. Run: npm run pack:doctor -- --protocol <protocol-id>');
  console.log('8. Run: npm run pack:check');
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
